# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AvenzaKMZImporter
                                 A QGIS plugin
 This plugin import features from KML e KMZ files from Avenza Maps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-26
        copyright            : (C) 2023 by Andrés de Medeiros Leite
        email                : leite.m.andres@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AvenzaKMZImporter class from file AvenzaKMZImporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .avenza_kmz_importer import AvenzaKMZImporter
    return AvenzaKMZImporter(iface)
